# Generated by Django 5.0.4 on 2024-05-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="escaperoom",
            name="availability",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="escaperoom",
            name="difficulty",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="escaperoom",
            name="theme",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
