# Generated by Django 5.0.4 on 2024-05-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancellation_requested",
            field=models.BooleanField(default=False),
        ),
    ]
