# Generated by Django 5.0.4 on 2024-05-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "booking",
            "0002_escaperoom_availability_alter_escaperoom_difficulty_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="escaperoom",
            name="theme",
        ),
        migrations.AlterField(
            model_name="escaperoom",
            name="difficulty",
            field=models.IntegerField(),
        ),
    ]
